### ISSUE TITLE
set_seconds causing a crash

### ISSUE THREAD

**Issue by jimboca** [jimboca/udi-wirelesstag-poly#10]
2018-03-03 12:16:51,862 DEBUG    wtController:shortPoll: discover thread is done...
2018-03-03 12:16:51,879 ERROR    Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 611, in _parseInput
    self.shortPoll()
  File "/home/pi/development/udi-wirelesstag-poly/wt_nodes/wtController.py", line 138, in shortPoll
    self.nodes[address].shortPoll()
  File "/home/pi/development/udi-wirelesstag-poly/wt_nodes/wTagManager.py", line 127, in shortPoll
    tag.shortPoll()
  File "/home/pi/development/udi-wirelesstag-poly/wt_nodes/wTag.py", line 210, in shortPoll
    self.set_seconds()
  File "/home/pi/development/udi-wirelesstag-poly/wt_nodes/wTag.py", line 513, in set_seconds
    value = int(time.time()) - self.time

**Comment by jimboca** [comment]
With the fix, the seconds since last update will be -1 if no update has been seen from the tag.  The last update time should be retained across reboots so it should never go to -1 except after initial discovery until an update is seen.
