### ISSUE TITLE
Change debug/logging mode broken

### ISSUE THREAD

**Issue by jimboca** [jimboca/udi-wirelesstag-poly#2]
2018-03-02 17:44:32,483 INFO     wtController:cmd_set_debug_mode: 0
2018-03-02 17:44:32,493 ERROR    Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 603, in _parseInput
    self.nodes[input[key]['address']].runCmd(input[key])
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 510, in runCmd
    fun(self, command)
  File "/home/pi/development/udi-wirelesstag-poly/wt_nodes/wtController.py", line 426, in cmd_set_debug_mode
    self.set_debug_mode(val)
  File "/home/pi/development/udi-wirelesstag-poly/wt_nodes/wtController.py", line 369, in set_debug_mode
    self.set_all_logs(logging.DEBUG)
AttributeError: 'wtController' object has no attribute 'set_all_logs'

**Comment by jimboca** [comment]
Fixed in 0.0.11.  Commits referenced #8 which doesn't exist...
